# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import partnerProvisioning_pb2 as partnerProvisioning__pb2


class PpsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PartnerProvisioning = channel.unary_unary(
                '/pps.PpsService/PartnerProvisioning',
                request_serializer=partnerProvisioning__pb2.PpsRequest.SerializeToString,
                response_deserializer=partnerProvisioning__pb2.PpsResponse.FromString,
                )


class PpsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PartnerProvisioning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PpsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PartnerProvisioning': grpc.unary_unary_rpc_method_handler(
                    servicer.PartnerProvisioning,
                    request_deserializer=partnerProvisioning__pb2.PpsRequest.FromString,
                    response_serializer=partnerProvisioning__pb2.PpsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pps.PpsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PpsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PartnerProvisioning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pps.PpsService/PartnerProvisioning',
            partnerProvisioning__pb2.PpsRequest.SerializeToString,
            partnerProvisioning__pb2.PpsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
